### ISSUE TITLE
想问一下有办法在linux上部署嘛

### ISSUE THREAD

**Issue by suansuanru9999** [RengarLee/SplatoonBot#8]

**Comment by suansuanru9999** [comment]
在azure上已搭建完成，日志里显示成功（可用），go-cqhttp也已配置好http设置，防火墙端口都打开

  - http: # HTTP 通信设置
      address: 127.0.0.1:5700 # HTTP监听地址

但是输入图和工之后，机器人貌似没有正常工作。azure上的url进去也是空白，请问这是正常的嘛

**Comment by suansuanru9999** [comment]
在azure上已搭建完成，日志里显示成功（可用）

go-cqhttp也已配置好http设置，防火墙端口都打开

http: # HTTP 通信设置
address: 127.0.0.1:5700 # HTTP监听地址

azure上的url进去也是空白，请问这是正常的嘛

输入图和工之后，机器人貌似没有正常工作

想请问下具体的对接步骤，还是说go-cqhttp还需要什么对接的设置

**Comment by RengarLee** [comment]
@suansuanru9999 

> azure上的url进去也是空白，请问这是正常的嘛
正常的，目前设置为非测试环境不生成Swagger文件,之后会考虑移除该设置。

如果确认站点部署没有问题，请检查Readme.md中所提的appsettings.json中的CqHttp.URL是否修改为go-cqhttp的主机地址。

**Comment by RengarLee** [comment]
今天晚上我完善该站点对接go-cqhttp的文档，方便您的对接。

**Comment by suansuanru9999** [comment]
> @suansuanru9999
> 
> > azure上的url进去也是空白，请问这是正常的嘛
> > 正常的，目前设置为非测试环境不生成Swagger文件,之后会考虑移除该设置。
> 
> 如果确认站点部署没有问题，请检查Readme.md中所提的appsettings.json中的CqHttp.URL是否修改为go-cqhttp的主机地址。

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "CqHttp": {
    "URL": "http://我的服务器地址:5700"
  }
}

也已经修改了，go-cqhttp里显示
[2022-09-20 17:27:47] [INFO]: CQ HTTP 服务器已启动: 127.0.0.1:5700 
就是bot没有任何反应

**Comment by suansuanru9999** [comment]
> 今天晚上我完善该站点对接go-cqhttp的文档，方便您的对接。

感谢回复，那我先等您晚上更新完文档再尝试，谢谢

**Comment by RengarLee** [comment]
@suansuanru9999 您好 文档已完善，请查阅。如果有什么疑问，欢迎提问。

**Comment by suansuanru9999** [comment]
启动go-cqhttp遇到这个问题
time="2022-09-20T21:17:54+08:00" level=fatal msg="配置文件不合法!yaml: line 2: did not find expected key"

配置文件如下
- http: # HTTP 通信设置
      address: 0.0.0.0:5700 # HTTP监听地址
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
      - url: 'http://splatoon3bot.azurewebsites.net:5102'                # 地址
        secret: ''             # 密钥
        max-retries: 3         # 最大重试，0 时禁用
        retries-interval: 1500 # 重试时间，单位毫秒，0 时立即

他提示的key是不是就是密钥，我在azure上应该设置什么

**Comment by suansuanru9999** [comment]
已部署成功，非常感谢耐心解答

一个小建议，武器图片有点太大了，刷屏了观感不太好

**Comment by suansuanru9999** [comment]
还有真格的开始结束时间显示好像也不对，现在这个时间点显示am4:00开始 am6:00结束
